name: multipack
description: A tool for monorepo management. Link local packages and execute commands in topological order.
version: 0.1.4
homepage: https://github.com/gql-dart/multipack
environment: 
  sdk: '>=2.8.0 <3.0.0'
dependencies: 
  ansicolor: ^1.0.2
  args: ^1.6.0
  directed_graph: ^0.2.3
  meta: ^1.0.0
  pubspec: ^0.1.2
  pub_semver: ^1.4.4
  path: ^1.6.4
dev_dependencies: 
  gql_pedantic: ^1.0.1
executables:
  multipack: null
